version: '3.8'
services:
  redis:
    image: bitnami/redis
    restart: always
    ports: [ '6379:6379' ]
    volumes: [ cache:/data ]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  cache:
    driver: local
